[package]
name = "tpm"
version = "0.1.0"
authors = ["Joe Richey <joerichey@google.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/josephlr/tpm"
documentation = "https://docs.rs/tpm"
homepage = "https://github.com/josephlr/tpm"
description = "High-level TPM2 TSS"
keywords = ["tpm", "tss", "tpm2"]
categories = ["cryptography", "no-std"]

[dependencies]
tpm_core = { path = "tpm_core", default-features = false }
tpm_os = { path = "tpm_os", optional = true }

[features]
default = ["std"]
std = ["alloc", "tpm_core/std", "tpm_os"]
alloc = ["tpm_core/alloc"]

[dev-dependencies]
once_cell = "0.2"

[workspace]
members = [
    "tpm_core",
    "tpm_os",
]

