[package]
name = "tpm"
version = "0.1.0"
authors = ["Joe Richey <joerichey@google.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/josephlr/tpm"
documentation = "https://docs.rs/tpm"
homepage = "https://github.com/josephlr/tpm"
description = "Pure Rust TPM2 TSS"
keywords = ["tpm", "tss", "tpm2"]
categories = ["cryptography", "no-std"]

[features]
default = ["std"]
std = ["once_cell"]
test-hardware = ["std"]

[dependencies]
cfg-if = "0.1.6"
once_cell = { version = "1.0.1", optional = true }

[dev-dependencies]
tpm-simulator = { path = "simulator" }

[workspace]
members = ["simulator"]
